# Generated by Django 3.1.1 on 2020-10-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name_plural': 'Loại Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='variationmodel',
            options={'verbose_name_plural': 'Sản phẩm change'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Ảnh sản phẩm'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='trạng thái'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categorymodel', verbose_name='Loại sản phẩm'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default='', verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='giá tiền'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='variationmodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='variationmodel',
            name='inventory',
            field=models.IntegerField(default=0, verbose_name='Tồn kho'),
        ),
        migrations.AlterField(
            model_name='variationmodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Giá tiền'),
        ),
        migrations.AlterField(
            model_name='variationmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel', verbose_name='sản phẩm'),
        ),
        migrations.AlterField(
            model_name='variationmodel',
            name='sale_price',
            field=models.IntegerField(default=0, verbose_name='Giá sale'),
        ),
        migrations.AlterField(
            model_name='variationmodel',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Tiêu đề'),
        ),
    ]
